select test_fixture();
select fnb_cancel_unpaid_order_atomic(test_id(10),'Khách đổi ý',null,test_id(30),null);
select test_assert((select status = 'occupied' and current_order_id = test_id(11) from restaurant_tables where id=test_id(9)), 'Main cancel keeps split bill');
select test_assert((select status = 'pending' from kitchen_orders where id=test_id(11)), 'Sibling order unchanged');
select test_assert((select count(*)=1 and sum(amount)=20000 from pos_exception_events), 'One exception and original amount');
select test_assert((select count(*)=2 from kitchen_order_items), 'Item history preserved');
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'')','ORDER_ALREADY_CANCELLED');
select test_assert((select count(*)=1 from pos_exception_events), 'Retry does not duplicate exception');
select fnb_cancel_unpaid_order_atomic(test_id(11),'Khách đổi ý');
select test_assert((select status = 'available' and current_order_id is null from restaurant_tables where id=test_id(9)), 'Last cancellation releases table');

select test_fixture();
select fnb_cancel_unpaid_order_atomic(test_id(11),'Khách đổi ý');
select test_assert((select status='occupied' and current_order_id=test_id(10) from restaurant_tables where id=test_id(9)), 'Child cancel keeps parent');
select test_fixture();
update kitchen_orders set invoice_id=test_id(88) where id=test_id(11);
select fnb_cancel_unpaid_order_atomic(test_id(10),'Khách đổi ý');
select test_assert((select status='available' from restaurant_tables where id=test_id(9)), 'Paid sibling does not retain unpaid table');

select test_fixture();
select set_config('test.actor',test_id(4)::text,false);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'')','PERMISSION_DENIED');
select fnb_cancel_unpaid_order_atomic(test_id(10),'Khách đổi ý',null,null,test_id(40));
select test_assert((select requested_by=test_id(4) and approved_by=test_id(1) from pos_exception_events), 'Delegation records cashier and approver');
select test_assert((select status='occupied' from restaurant_tables where id=test_id(9)), 'OTP cancel preserves sibling');

select test_fixture();
select set_config('test.actor',test_id(4)::text,false);
update manager_otp_codes set issued_by=test_id(5);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'',null,null,test_id(40))','FNB_CANCEL_APPROVER_SCOPE_DENIED');
select test_assert((select count(*)=0 from pos_exception_events), 'Invalid approver leaves no event');
select test_assert((select status='ready' from kitchen_orders where id=test_id(10)), 'Invalid approver leaves order untouched');
select test_fixture();
select set_config('test.actor',test_id(5)::text,false);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'')','FNB_CANCEL_BRANCH_ACCESS_DENIED');
select test_fixture();
select set_config('test.actor',test_id(4)::text,false);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(11),''Khách đổi ý'',null,null,test_id(40))','OTP_TARGET_MISMATCH');
select test_fixture();
update kitchen_orders set invoice_id=test_id(88) where id=test_id(10);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'')','ORDER_ALREADY_PAID');
select test_fixture();
update kitchen_orders set merged_into_id=test_id(11) where id=test_id(10);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'')','FNB_CANCEL_ORDER_MERGED');
select test_fixture();
update restaurant_tables set branch_id=test_id(99);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'')','FNB_CANCEL_TABLE_SCOPE_DENIED');
select test_fixture();
update shifts set cashier_id=test_id(4);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'',null,test_id(30))','FNB_CANCEL_SHIFT_NOT_OPEN_FOR_USER_BRANCH');
select test_fixture();
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),'' '')','CANCEL_REASON_REQUIRED');
select test_assert((select count(*)=0 from pos_exception_events), 'Rejected cancellation has no business write');
select test_fixture();
update profiles set is_active=false where id=test_id(1);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'')','ACTIVE_PROFILE_REQUIRED');
select test_fixture();
select set_config('test.actor','',false);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'')','AUTH_REQUIRED');
select test_fixture();
select set_config('test.actor',test_id(4)::text,false);
update manager_otp_codes set target_meta='{}'::jsonb;
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'',null,null,test_id(40))','FNB_CANCEL_OTP_SCOPE_REQUIRED');
select test_assert((select count(*)=0 from pos_exception_events),'Unbound OTP leaves no event');
select test_fixture();
select set_config('test.actor',test_id(4)::text,false);
update manager_otp_codes set branch_id=test_id(99);
select test_reject('select fnb_cancel_unpaid_order_atomic(test_id(10),''Khách đổi ý'',null,null,test_id(40))','FNB_CANCEL_OTP_SCOPE_REQUIRED');
select test_assert((select status='ready' from kitchen_orders where id=test_id(10)),'Wrong branch OTP leaves bill untouched');
select 'PASS: unpaid cancellation scope, split table, OTP, retry and history' as result;
