import { describe, expect, it } from "vitest";
import {
  buildFnbStoredItemNote,
  getFnbFreeTextNote,
} from "@/lib/fnb-item-note";

const MODIFIERS = ["Mức đá: Bình thường", "Mức đường: 80%"];

describe("FnB item notes", () => {
  it("stores only the cashier note when structured modifiers are available", () => {
    expect(buildFnbStoredItemNote("Không ống hút", MODIFIERS, true)).toBe("Không ống hút");
    expect(buildFnbStoredItemNote("", MODIFIERS, true)).toBeUndefined();
  });

  it("keeps modifier text in the legacy path without a structured snapshot", () => {
    expect(buildFnbStoredItemNote("Không ống hút", ["Ít đá", "80% đường"], false)).toBe(
      "Ít đá, 80% đường — Không ống hút",
    );
  });

  it("removes an exact duplicate generated by older POS builds", () => {
    expect(getFnbFreeTextNote(MODIFIERS.join(", "), MODIFIERS)).toBeUndefined();
  });

  it("preserves a cashier note appended after legacy modifier text", () => {
    expect(
      getFnbFreeTextNote(`${MODIFIERS.join(", ")} — Không ống hút`, MODIFIERS),
    ).toBe("Không ống hút");
  });

  it("does not alter unrelated free text", () => {
    expect(getFnbFreeTextNote("Mang ra cùng lúc", MODIFIERS)).toBe("Mang ra cùng lúc");
  });
});
