import { User, Employee } from "./utils";

// Mock employees data
export const employeesData: Employee[] = [
    {
        id: "NV001",
        name: "Nguyễn Văn An",
        email: "an.nguyen@company.vn",
        department: "Kỹ thuật",
        position: "Senior Developer",
        phone: "0901 234 567",
        status: "active",
        joinDate: "2022-03-15",
        address: "123 Nguyễn Huệ, Quận 1, TP.HCM",
        avatar: "NVA",
    },
    {
        id: "NV002",
        name: "Trần Thị Bình",
        email: "binh.tran@company.vn",
        department: "Nhân sự",
        position: "HR Manager",
        phone: "0912 345 678",
        status: "active",
        joinDate: "2021-06-01",
        address: "456 Lê Lợi, Quận 3, TP.HCM",
        avatar: "TTB",
    },
    {
        id: "NV003",
        name: "Lê Hoàng Cường",
        email: "cuong.le@company.vn",
        department: "Kinh doanh",
        position: "Sales Executive",
        phone: "0923 456 789",
        status: "active",
        joinDate: "2023-01-10",
        address: "789 Hai Bà Trưng, Quận 1, TP.HCM",
        avatar: "LHC",
    },
    {
        id: "NV004",
        name: "Phạm Minh Dũng",
        email: "dung.pham@company.vn",
        department: "Kỹ thuật",
        position: "Junior Developer",
        phone: "0934 567 890",
        status: "probation",
        joinDate: "2024-09-01",
        address: "321 Võ Văn Tần, Quận 3, TP.HCM",
        avatar: "PMD",
    },
    {
        id: "NV005",
        name: "Hoàng Thị Hoa",
        email: "hoa.hoang@company.vn",
        department: "Kế toán",
        position: "Accountant",
        phone: "0945 678 901",
        status: "active",
        joinDate: "2020-11-20",
        address: "654 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM",
        avatar: "HTH",
    },
    {
        id: "NV006",
        name: "Vũ Đức Minh",
        email: "minh.vu@company.vn",
        department: "Marketing",
        position: "Marketing Specialist",
        phone: "0956 789 012",
        status: "inactive",
        joinDate: "2019-08-05",
        address: "987 Nam Kỳ Khởi Nghĩa, Quận 3, TP.HCM",
        avatar: "VDM",
    },
];

// Mock users data with different roles
export const usersData: User[] = [
    {
        id: "USR001",
        username: "admin",
        email: "admin@company.vn",
        password: "admin123",
        fullName: "Admin System",
        role: "admin",
        employeeId: null,
        isActive: true,
        createdAt: "2020-01-01",
    },
    {
        id: "USR002",
        username: "ketoan",
        email: "ketoan@company.vn",
        password: "ketoan123",
        fullName: "Hoàng Thị Hoa",
        role: "accountant",
        employeeId: "NV005",
        isActive: true,
        createdAt: "2020-11-20",
    },
    {
        id: "USR003",
        username: "qlcn",
        email: "qlcn@company.vn",
        password: "qlcn123",
        fullName: "Trần Thị Bình",
        role: "branch_manager",
        employeeId: "NV002",
        isActive: true,
        createdAt: "2021-06-01",
    },
    {
        id: "USR004",
        username: "member",
        email: "member@company.vn",
        password: "member123",
        fullName: "Nguyễn Văn An",
        role: "member",
        employeeId: "NV001",
        isActive: true,
        createdAt: "2022-03-15",
    },
];
