-- READ-ONLY: exact named-argument contracts used by the current web.
-- It checks live Supabase metadata only and changes no business data.

with required(function_name, sent_args) as (
  values
    ('adopt_pos_draft_session_atomic_v2', array['p_client_session_id', 'p_expected_revision', 'p_invoice_id']::text[]),
    ('allocate_lots_fifo', array['p_branch_id', 'p_product_id', 'p_quantity', 'p_source_id', 'p_source_type', 'p_tenant_id']::text[]),
    ('apply_coupon_atomic', array['p_code', 'p_customer_id', 'p_discount_amount', 'p_invoice_id']::text[]),
    ('apply_disposal_export_atomic', array['p_disposal_id']::text[]),
    ('apply_internal_export_atomic', array['p_export_id']::text[]),
    ('apply_inventory_check_atomic', array['p_check_id', 'p_created_by', 'p_tenant_id']::text[]),
    ('apply_manual_stock_movement_atomic', array['p_branch_id', 'p_created_by', 'p_items', 'p_tenant_id']::text[]),
    ('assign_delivery_staff_to_order', array['p_kitchen_order_id', 'p_staff_id']::text[]),
    ('attach_invoice_shipment_atomic', array['p_delivery_fee', 'p_invoice_id', 'p_note', 'p_partner_id', 'p_receiver_address', 'p_receiver_name', 'p_receiver_phone']::text[]),
    ('bulk_cleanup_test_products_atomic', array['p_product_ids']::text[]),
    ('bulk_create_adjustment_lots_atomic', array['p_default_note', 'p_items']::text[]),
    ('bulk_delete_products_atomic', array['p_product_ids']::text[]),
    ('bulk_force_delete_products_atomic', array['p_product_ids']::text[]),
    ('calculate_bom_cost', array['p_bom_id']::text[]),
    ('cancel_cash_transaction', array['p_cash_id', 'p_reason']::text[]),
    ('cancel_disposal_export_atomic_v2', array['p_disposal_id', 'p_reason']::text[]),
    ('cancel_draft_invoice_atomic', array['p_invoice_id', 'p_reason']::text[]),
    ('cancel_internal_export_atomic_v2', array['p_export_id', 'p_reason']::text[]),
    ('cancel_internal_sale_atomic', array['p_internal_sale_id', 'p_reason']::text[]),
    ('cancel_inventory_check_atomic', array['p_check_id']::text[]),
    ('cancel_legacy_sales_order_atomic', array['p_order_id', 'p_reason']::text[]),
    ('change_my_pos_pin', array['p_new_pin', 'p_old_pin']::text[]),
    ('change_production_status_atomic', array['p_new_status', 'p_production_order_id']::text[]),
    ('check_expiring_lots', array['p_days_threshold', 'p_tenant_id']::text[]),
    ('cleanup_expired_auto_drafts', array['p_days', 'p_tenant_id']::text[]),
    ('cleanup_test_product_atomic', array['p_product_id']::text[]),
    ('close_purchase_order_short', array['p_order_id', 'p_reason']::text[]),
    ('close_shift_atomic', array['p_actual_cash', 'p_note', 'p_shift_id']::text[]),
    ('complete_delivery_for_order', array['p_kitchen_order_id']::text[]),
    ('complete_draft_atomic_v5', array['p_allow_bom_shortage', 'p_amount_tendered', 'p_client_session_id', 'p_coupon_code', 'p_customer_credit', 'p_customer_id', 'p_discount_otp_id', 'p_discount_reason', 'p_discount_source', 'p_expected_revision', 'p_expected_total', 'p_invoice_id', 'p_items', 'p_loyalty_points', 'p_method', 'p_order_discount', 'p_order_vat_rate', 'p_paid', 'p_payment_breakdown', 'p_promotion_id', 'p_shift_id', 'p_shipping_fee']::text[]),
    ('complete_legacy_sales_order_atomic', array['p_order_id']::text[]),
    ('complete_production_atomic', array['p_completed_qty', 'p_expiry_date', 'p_lot_number', 'p_manufactured_date', 'p_production_order_id']::text[]),
    ('complete_production_order', array['p_completed_qty', 'p_expiry_date', 'p_lot_number', 'p_manufactured_date', 'p_production_order_id']::text[]),
    ('complete_stock_transfer_atomic', array['p_created_by', 'p_tenant_id', 'p_transfer_id']::text[]),
    ('consume_production_materials', array['p_production_order_id']::text[]),
    ('create_disposal_export_atomic', array['p_branch_id', 'p_items', 'p_note', 'p_reason']::text[]),
    ('create_internal_export_atomic', array['p_branch_id', 'p_department', 'p_items', 'p_note']::text[]),
    ('create_internal_sale_atomic', array['p_created_by', 'p_from_branch_id', 'p_int_customer_id', 'p_int_customer_name', 'p_int_supplier_id', 'p_int_supplier_name', 'p_items', 'p_note', 'p_paid_full', 'p_payment_method', 'p_tenant_id', 'p_to_branch_id']::text[]),
    ('create_manual_cash_transaction_atomic', array['p_amount', 'p_branch_id', 'p_category', 'p_counterparty', 'p_note', 'p_payment_method', 'p_requested_code', 'p_transaction_date', 'p_type']::text[]),
    ('create_production_order_atomic', array['p_input']::text[]),
    ('create_sales_return_atomic', array['p_invoice_id', 'p_items', 'p_note', 'p_reason', 'p_refund_amount', 'p_refund_payment_method', 'p_shift_id']::text[]),
    ('create_stock_transfer_atomic', array['p_from_branch_id', 'p_items', 'p_note', 'p_to_branch_id']::text[]),
    ('create_supplier_return_atomic', array['p_items', 'p_note', 'p_payment_method', 'p_purchase_order_id', 'p_reason']::text[]),
    ('delete_customer_atomic', array['p_customer_id', 'p_otp_id']::text[]),
    ('delete_product_atomic', array['p_otp_id', 'p_product_id']::text[]),
    ('delete_product_platform_prices', array['p_platform', 'p_product_ids']::text[]),
    ('delete_role_atomic', array['p_role_id']::text[]),
    ('delete_supplier_atomic', array['p_supplier_id']::text[]),
    ('duplicate_invoice_to_order_atomic', array['p_source_invoice_id', 'p_target_branch_id']::text[]),
    ('earn_loyalty_points', array['p_amount', 'p_customer_id', 'p_invoice_id']::text[]),
    ('fnb_cancel_unpaid_order_atomic', array['p_order_id', 'p_otp_id', 'p_reason_code', 'p_reason_note', 'p_shift_id']::text[]),
    ('fnb_complete_payment_atomic_v2', array['p_coupon_code', 'p_coupon_discount', 'p_created_by', 'p_customer_id', 'p_customer_name', 'p_discount_amount', 'p_kitchen_order_id', 'p_note', 'p_paid', 'p_payment_breakdown', 'p_payment_method', 'p_promotion_discount', 'p_promotion_free_value', 'p_promotion_id', 'p_shift_id', 'p_tip_amount']::text[]),
    ('fnb_send_to_kitchen_atomic_v2', array['p_branch_id', 'p_delivery_distance_tier', 'p_delivery_fee', 'p_delivery_platform', 'p_delivery_staff_id', 'p_existing_order_id', 'p_idempotency_key', 'p_items', 'p_note', 'p_order_type', 'p_platform_commission_percent', 'p_table_id']::text[]),
    ('fnb_send_to_kitchen_atomic_v2', array['p_branch_id', 'p_delivery_distance_tier', 'p_delivery_fee', 'p_delivery_platform', 'p_delivery_staff_id', 'p_idempotency_key', 'p_items', 'p_note', 'p_order_type', 'p_platform_commission_percent', 'p_table_id']::text[]),
    ('fnb_set_delivery_pricing_v2', array['p_commission_percent', 'p_delivery_fee', 'p_distance_tier', 'p_kitchen_order_id', 'p_platform']::text[]),
    ('fnb_transfer_table_atomic', array['p_from_table_id', 'p_order_id', 'p_tenant_id', 'p_to_table_id']::text[]),
    ('fnb_update_kitchen_item_status_v2', array['p_item_id', 'p_new_status']::text[]),
    ('fnb_update_kitchen_order_status_v2', array['p_new_status', 'p_order_id']::text[]),
    ('fnb_void_invoice_atomic', array['p_branch_id', 'p_invoice_id', 'p_kitchen_order_id', 'p_otp_id', 'p_shift_id', 'p_tenant_id', 'p_void_reason', 'p_voided_by']::text[]),
    ('force_delete_product_atomic', array['p_product_id']::text[]),
    ('get_active_bom_for_branch', array['p_branch_id', 'p_product_id']::text[]),
    ('get_bom_availability_batch', array['p_branch_id', 'p_sku_ids', 'p_tenant_id']::text[]),
    ('get_branch_profit_and_loss_report', array['p_date_from', 'p_date_to']::text[]),
    ('get_consolidated_profit_and_loss_report', array['p_current_from', 'p_current_to', 'p_previous_from', 'p_previous_to']::text[]),
    ('get_customer_cohort_report', array['p_branch_id', 'p_months']::text[]),
    ('get_customer_product_detail_page', array['p_branch_id', 'p_customer_id', 'p_date_from', 'p_date_to', 'p_limit', 'p_offset', 'p_search', 'p_sort']::text[]),
    ('get_customer_product_export_page', array['p_branch_id', 'p_date_from', 'p_date_to', 'p_limit', 'p_offset']::text[]),
    ('get_customer_product_report', array['p_branch_id', 'p_date_from', 'p_date_to', 'p_limit', 'p_offset', 'p_search', 'p_sort']::text[]),
    ('get_disposal_loss_report', array['p_branch_id', 'p_date_from', 'p_date_to']::text[]),
    ('get_email_by_phone', array['p_phone']::text[]),
    ('get_finance_dashboard_report', array['p_branch_id', 'p_current_from', 'p_current_to', 'p_previous_from', 'p_previous_to']::text[]),
    ('get_financial_analysis_details_report', array['p_branch_id', 'p_date_from', 'p_date_to', 'p_exclude_internal', 'p_limit']::text[]),
    ('get_fnb_serve_time_report', array['p_branch_id', 'p_date_from', 'p_date_to']::text[]),
    ('get_inventory_aging_report', array['p_branch_id']::text[]),
    ('get_inventory_variance_report', array['p_branch_id', 'p_date_from', 'p_date_to']::text[]),
    ('get_lots_for_product', array['p_branch_id', 'p_product_id']::text[]),
    ('get_payable_aging_report', array['p_as_of_date', 'p_branch_id']::text[]),
    ('get_platform_commission_report', array['p_branch_id', 'p_date_from', 'p_date_to']::text[]),
    ('get_pos_invoice_integrity_report', array['p_branch_id', 'p_from', 'p_limit', 'p_to']::text[]),
    ('get_products_with_branch_stock', array['p_branch_id', 'p_category_id', 'p_only_without_lots', 'p_supplier_id']::text[]),
    ('get_profit_and_loss_report', array['p_branch_id', 'p_current_from', 'p_current_to', 'p_previous_from', 'p_previous_to']::text[]),
    ('get_receivable_aging_report', array['p_as_of_date', 'p_branch_id']::text[]),
    ('get_recent_manager_otps', array['p_limit']::text[]),
    ('get_rfm_report', array['p_branch_id', 'p_date_from', 'p_date_to']::text[]),
    ('get_sales_report_invoice_page', array['p_branch_id', 'p_date_from', 'p_date_to', 'p_limit', 'p_offset']::text[]),
    ('get_sales_report_summary', array['p_branch_id', 'p_date_from', 'p_date_to']::text[]),
    ('get_sales_return_report', array['p_branch_id', 'p_date_from', 'p_date_to']::text[]),
    ('get_staff_revenue_report', array['p_branch_id', 'p_date_from', 'p_date_to', 'p_source']::text[]),
    ('get_stock_card_v2', array['p_branch_id', 'p_product_id']::text[]),
    ('get_stockout_forecast', array['p_branch_id', 'p_days', 'p_limit', 'p_product_type', 'p_tenant_id']::text[]),
    ('get_user_effective_permissions', array['p_user_id']::text[]),
    ('get_user_permissions', array['p_user_id']::text[]),
    ('get_vat_report', array['p_branch_id', 'p_date_from', 'p_date_to']::text[]),
    ('get_xnt_report', array['p_branch_id', 'p_date_from', 'p_date_to', 'p_search']::text[]),
    ('increment_promotion_usage', array['p_promotion_id']::text[]),
    ('initialize_managed_user_atomic', array['p_branch_ids', 'p_email', 'p_full_name', 'p_phone', 'p_role_id', 'p_target_user_id']::text[]),
    ('issue_manager_otp', array['p_action_code', 'p_branch_id', 'p_target_invoice_code', 'p_target_kitchen_order_number', 'p_target_meta']::text[]),
    ('list_pos_pin_users', array['p_branch_id']::text[]),
    ('mark_fnb_table_available_atomic', array['p_table_id']::text[]),
    ('mark_overdue_shifts_for_branch', array['p_branch_id']::text[]),
    ('mkt_add_readiness_item', array['p_campaign_id', 'p_due_at', 'p_required_branch_id', 'p_required_role', 'p_title']::text[]),
    ('mkt_assign_channel_planning', array['p_header', 'p_owner_id', 'p_reviewer_id', 'p_work_package_id']::text[]),
    ('mkt_audit_execute_scenario', array['p_run_id', 'p_scenario_key']::text[]),
    ('mkt_campaign_plan_delete', array['p_id']::text[]),
    ('mkt_campaign_plan_upsert', array['p_campaign_id', 'p_id', 'p_name', 'p_objective', 'p_owner_id', 'p_parent_plan_id', 'p_timeframe_end', 'p_timeframe_start']::text[]),
    ('mkt_change_campaign_status', array['p_campaign_id', 'p_override_reason', 'p_status']::text[]),
    ('mkt_claim_audit_access_token', array['p_token_hash']::text[]),
    ('mkt_claim_outbox_events', array['p_limit', 'p_worker_id']::text[]),
    ('mkt_confirm_readiness_item', array['p_campaign_id', 'p_item_id', 'p_note']::text[]),
    ('mkt_consume_telegram_link_token', array['p_chat_id', 'p_telegram_user_id', 'p_token_hash', 'p_update_id', 'p_username']::text[]),
    ('mkt_create_audit_access_token', array['p_created_by', 'p_expires_at', 'p_max_runs', 'p_owner_tenant_id', 'p_sandbox_id', 'p_token_hash']::text[]),
    ('mkt_create_campaign', array['p_branch_id', 'p_budget', 'p_name', 'p_objective', 'p_owner_id', 'p_readiness_items', 'p_timeframe_end', 'p_timeframe_start']::text[]),
    ('mkt_create_content_item', array['p_campaign_id', 'p_channel_type', 'p_pillar_id', 'p_risk_level', 'p_title', 'p_work_package_id']::text[]),
    ('mkt_create_manual_task', array['p_assignee_id', 'p_campaign_id', 'p_description', 'p_due_at', 'p_reviewer_id', 'p_task_type', 'p_title', 'p_work_package_id', 'p_workload_points']::text[]),
    ('mkt_create_telegram_link_token', array['p_expires_at', 'p_token_hash']::text[]),
    ('mkt_create_work_package', array['p_campaign_id', 'p_campaign_plan_id', 'p_channel_type', 'p_owner_id', 'p_reviewer_id', 'p_target_output', 'p_title']::text[]),
    ('mkt_delete_campaign', array['p_campaign_id', 'p_reason']::text[]),
    ('mkt_delete_content_item', array['p_content_id']::text[]),
    ('mkt_delete_plan_progress_report', array['p_report_id']::text[]),
    ('mkt_delete_readiness_item', array['p_item_id']::text[]),
    ('mkt_delete_task', array['p_reason', 'p_task_id']::text[]),
    ('mkt_delete_work_package', array['p_reason', 'p_work_package_id']::text[]),
    ('mkt_document_register', array['p_campaign_id', 'p_category', 'p_description', 'p_external_id', 'p_external_url', 'p_mime_type', 'p_size_bytes', 'p_source_type', 'p_storage_path', 'p_thumbnail_url', 'p_title']::text[]),
    ('mkt_document_remove', array['p_id']::text[]),
    ('mkt_document_set_status', array['p_id', 'p_status']::text[]),
    ('mkt_get_exception_log', array['p_campaign_id', 'p_limit']::text[]),
    ('mkt_get_leader_queue', array['p_branch_id', 'p_limit', 'p_offset']::text[]),
    ('mkt_get_my_context', array[]::text[]),
    ('mkt_media_register', array['p_campaign_id', 'p_content_item_id', 'p_external_id', 'p_external_url', 'p_file_name', 'p_kind', 'p_mime_type', 'p_size_bytes', 'p_source_type', 'p_storage_path', 'p_thumbnail_url']::text[]),
    ('mkt_media_remove', array['p_id']::text[]),
    ('mkt_media_set_status', array['p_id', 'p_status']::text[]),
    ('mkt_open_plan_change_request', array['p_plan_id', 'p_reason']::text[]),
    ('mkt_owner_add_subplan', array['p_campaign_plan_id', 'p_channel_type', 'p_title']::text[]),
    ('mkt_pillar_angle_remove', array['p_id']::text[]),
    ('mkt_pillar_angle_upsert', array['p_channels', 'p_description', 'p_format', 'p_funnel', 'p_guideline', 'p_id', 'p_pillar_id', 'p_sort_order', 'p_title']::text[]),
    ('mkt_pillar_deactivate', array['p_id']::text[]),
    ('mkt_pillar_upsert', array['p_code', 'p_color', 'p_description', 'p_id', 'p_name', 'p_sort_order']::text[]),
    ('mkt_ping_team_member', array['p_message', 'p_user_id']::text[]),
    ('mkt_read_audit_access_token', array['p_token_hash']::text[]),
    ('mkt_reconcile_plan_task', array['p_decision', 'p_new_assignee_id', 'p_plan_id', 'p_reason', 'p_task_id']::text[]),
    ('mkt_remind_readiness_item', array['p_campaign_id', 'p_item_id']::text[]),
    ('mkt_review_content', array['p_action', 'p_comment', 'p_content_id', 'p_content_version_id']::text[]),
    ('mkt_review_plan', array['p_action', 'p_comment', 'p_plan_id', 'p_version_id']::text[]),
    ('mkt_revoke_audit_access_token', array['p_access_id', 'p_owner_tenant_id', 'p_revoked_by']::text[]),
    ('mkt_save_plan_items', array['p_expected_version', 'p_header', 'p_items', 'p_plan_id', 'p_stages']::text[]),
    ('mkt_save_plan_strategy', array['p_budget_planned', 'p_expected_version', 'p_kpis', 'p_plan_id', 'p_strategy_summary']::text[]),
    ('mkt_split_work_package', array['p_tasks', 'p_template_code', 'p_work_package_id']::text[]),
    ('mkt_submit_plan', array['p_expected_version', 'p_plan_id']::text[]),
    ('mkt_submit_plan_progress', array['p_health', 'p_issues', 'p_kpi_actuals', 'p_next_steps', 'p_plan_id', 'p_summary']::text[]),
    ('mkt_unlink_telegram', array[]::text[]),
    ('mkt_update_campaign', array['p_campaign_id', 'p_patch']::text[]),
    ('mkt_waive_readiness_item', array['p_campaign_id', 'p_item_id', 'p_reason']::text[]),
    ('mkt_work_package_set_campaign_plan', array['p_campaign_plan_id', 'p_work_package_id']::text[]),
    ('next_code', array['p_entity_type', 'p_tenant_id']::text[]),
    ('next_group_code', array['p_group_code', 'p_prefix', 'p_tenant_id']::text[]),
    ('next_simple_code', array['p_prefix', 'p_tenant_id']::text[]),
    ('patch_tenant_settings_atomic', array['p_replace', 'p_section', 'p_value']::text[]),
    ('peek_next_group_code', array['p_group_code', 'p_prefix', 'p_tenant_id']::text[]),
    ('peek_next_simple_code', array['p_prefix', 'p_tenant_id']::text[]),
    ('pipeline_get_allowed_transitions', array['p_pipeline_item_id']::text[]),
    ('pipeline_get_board', array['p_pipeline_id']::text[]),
    ('pipeline_get_timeline', array['p_pipeline_item_id']::text[]),
    ('pipeline_transition', array['p_dimensions', 'p_note', 'p_pipeline_item_id', 'p_to_stage_id']::text[]),
    ('pos_complete_checkout_atomic_v3', array['p_allow_bom_shortage', 'p_amount_tendered', 'p_branch_id', 'p_client_session_id', 'p_coupon_code', 'p_customer_credit', 'p_customer_id', 'p_discount_otp_id', 'p_discount_reason', 'p_discount_source', 'p_items', 'p_loyalty_points', 'p_note', 'p_order_discount', 'p_order_vat_rate', 'p_paid', 'p_payment_breakdown', 'p_payment_method', 'p_promotion_id', 'p_shift_id', 'p_shipping_fee', 'p_source']::text[]),
    ('receive_purchase_items_atomic', array['p_created_by', 'p_lines', 'p_order_id']::text[]),
    ('reconcile_pending_shift', array['p_actual_cash', 'p_note', 'p_reason', 'p_shift_id']::text[]),
    ('record_discount_audit', array['p_discount_amount', 'p_discount_percent', 'p_invoice_code', 'p_invoice_id', 'p_invoice_total', 'p_otp_id', 'p_reason']::text[]),
    ('redeem_loyalty_points', array['p_customer_id', 'p_invoice_id', 'p_points']::text[]),
    ('remove_user_pos_pin', array['p_target_user_id']::text[]),
    ('report_cogs_by_bom', array['p_branch_id', 'p_from_date', 'p_to_date']::text[]),
    ('report_nvl_consumption_by_branch', array['p_branch_id', 'p_from_date', 'p_to_date']::text[]),
    ('restore_product_atomic', array['p_product_id']::text[]),
    ('revert_production_materials', array['p_production_order_id', 'p_reason']::text[]),
    ('revert_received_purchase_order_atomic', array['p_allow_negative', 'p_order_id', 'p_user_id']::text[]),
    ('save_branch_atomic', array['p_branch_id', 'p_payload']::text[]),
    ('save_pos_draft_atomic_v3', array['p_auto_saved', 'p_branch_id', 'p_client_session_id', 'p_customer_id', 'p_expected_revision', 'p_invoice_id', 'p_items', 'p_note', 'p_order_discount', 'p_order_vat_rate', 'p_payment_method', 'p_shipping_fee']::text[]),
    ('save_purchase_order_atomic', array['p_branch_id', 'p_items', 'p_mark_ordered', 'p_note', 'p_order_discount', 'p_other_cost', 'p_paid_amount', 'p_payment_method', 'p_purchase_order_id', 'p_receive_now', 'p_requested_code', 'p_shipping_cost', 'p_supplier_id']::text[]),
    ('save_role_atomic', array['p_payload', 'p_permission_codes', 'p_role_id']::text[]),
    ('save_sales_order_atomic', array['p_branch_id', 'p_customer_id', 'p_delivery_fee', 'p_items', 'p_note', 'p_order_id', 'p_partner_id', 'p_receiver_address', 'p_receiver_name', 'p_receiver_phone', 'p_requested_code']::text[]),
    ('seed_default_agents', array['p_tenant_id']::text[]),
    ('seed_internal_entities', array['p_tenant_id']::text[]),
    ('set_branch_print_brand_atomic', array['p_branch_id', 'p_brand']::text[]),
    ('set_input_invoice_state_atomic', array['p_action', 'p_invoice_id', 'p_reason']::text[]),
    ('set_purchase_order_state_atomic', array['p_new_status', 'p_purchase_order_id', 'p_reason']::text[]),
    ('set_stock_transfer_state_atomic', array['p_new_status', 'p_transfer_id']::text[]),
    ('set_tenant_setting', array['p_description', 'p_key', 'p_value']::text[]),
    ('set_user_pos_pin', array['p_pin', 'p_target_user_id']::text[]),
    ('soft_delete_pos_draft_atomic', array['p_invoice_id', 'p_only_auto_saved']::text[]),
    ('split_kitchen_order_atomic', array['p_item_ids', 'p_mode', 'p_number_of_ways', 'p_order_id']::text[]),
    ('toggle_favorite', array['p_entity_id', 'p_entity_type']::text[]),
    ('update_branch_settings_atomic', array['p_branch_id', 'p_patch']::text[]),
    ('update_draft_invoice_atomic', array['p_invoice_id', 'p_patch']::text[]),
    ('update_managed_user_atomic', array['p_branch_ids', 'p_profile_patch', 'p_target_user_id']::text[]),
    ('update_own_profile_atomic', array['p_full_name', 'p_phone']::text[]),
    ('update_purchase_order_prices', array['p_items', 'p_note', 'p_order_discount', 'p_order_id', 'p_other_cost', 'p_shipping_cost', 'p_supplier_id', 'p_supplier_name']::text[]),
    ('update_received_purchase_order_atomic', array['p_note', 'p_payment_method', 'p_purchase_order_id', 'p_requested_paid']::text[]),
    ('update_shipping_order_status_atomic', array['p_next_status', 'p_note', 'p_shipping_order_id']::text[]),
    ('upsert_debt_opening_balance_atomic', array['p_amount', 'p_branch_id', 'p_note', 'p_opening_date', 'p_party_id', 'p_party_type']::text[]),
    ('upsert_product_platform_prices', array['p_rows']::text[]),
    ('validate_coupon', array['p_code', 'p_customer_id', 'p_order_amount']::text[]),
    ('verify_and_use_manager_otp', array['p_action_code', 'p_code', 'p_target_meta']::text[]),
    ('verify_pos_pin', array['p_branch_id', 'p_pin', 'p_user_id']::text[]),
    ('verify_stock_invariants', array['p_tenant_id', 'p_tolerance']::text[]),
    ('void_completed_invoice_atomic_v2', array['p_invoice_id', 'p_reason', 'p_refund_method', 'p_shift_id']::text[])
),
live as (
  select
    p.oid,
    p.proname as function_name,
    coalesce(p.proargnames[1:p.pronargs], array[]::text[]) as input_args,
    coalesce(
      p.proargnames[1:greatest(p.pronargs - p.pronargdefaults, 0)],
      array[]::text[]
    ) as required_args
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
)
select
  r.function_name,
  r.sent_args,
  exists (
    select 1
    from live l
    where l.function_name = r.function_name
      and r.sent_args <@ l.input_args
      and l.required_args <@ r.sent_args
  ) as exact_named_contract_ok,
  coalesce(
    (
      select array_agg(pg_get_function_identity_arguments(l.oid) order by l.oid)
      from live l
      where l.function_name = r.function_name
    ),
    array[]::text[]
  ) as live_signatures
from required r
where not exists (
  select 1
  from live l
  where l.function_name = r.function_name
    and r.sent_args <@ l.input_args
    and l.required_args <@ r.sent_args
)
order by r.function_name, r.sent_args;

